spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql 8.0+ should use this driver
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name:  gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
#  resources:
#    static-locations: classpath:/static/
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #数据插入的时候启动自增主键
server:
  port: 10001

logging:
  level:
     com.atguigu.gulimall.gulimallproduct: debug

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
