spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos的地址2
    gateway:
      routes:
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        - id: ware_route #/api/member/请求会转发到member服务
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member_route #/api/member/请求会转发到member服务
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: product_route #/api/gulimallproduct/请求会转发到product服务
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/** #/api/请求会转发到renren后端服务
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

        - id: gulimall_product_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

  application:
    name: gulimall-gateway
server:
  port: 88
